[package]
name = "colorizer"
version = "1.1.1"
authors = ["Anton Kulinsky <ankulinsky@gmail.com>"]
license = "MIT"
description = "A tool for highlighting words in the terminal"
readme = "README.md"
homepage = "https://github.com/kulinsky/colorizer"
repository = "https://github.com/kulinsky/colorizer"
keywords = ["cli", "highlight", "color", "terminal", "text"]
edition = "2018"
categories = ["command-line-utilities"]

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
serde={ version = "1.0.126", features = ["derive"] }
serde_json = "1.0.64"
ansi_term = "0.12.1"
clap = "3.0.0-beta.2"
anyhow = "1.0.41"
regex = "1.5.4"